import html, json
from pathlib import Path

def build(rows, output="docs/index.html"):
    data = [dict(r) for r in rows]
    safe_json = json.dumps(data).replace("</", "<\\/")
    page = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Summer 2027 Internship Scanner</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#18202a;background:#f5f7fb}body{margin:0}.wrap{max-width:1400px;margin:auto;padding:28px}.hero{background:#fff;border-radius:18px;padding:24px;box-shadow:0 8px 30px #0000000c}.hero h1{margin:0 0 8px}.muted{color:#667085}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}input,select,button{font:inherit;padding:10px 12px;border:1px solid #d0d5dd;border-radius:9px;background:#fff}input{min-width:280px;flex:1}button{cursor:pointer}.card{background:#fff;border-radius:14px;overflow:auto;box-shadow:0 5px 20px #0000000a}table{border-collapse:collapse;width:100%;min-width:1050px}th,td{text-align:left;padding:12px;border-bottom:1px solid #eaecf0;vertical-align:top}th{position:sticky;top:0;background:#f9fafb;cursor:pointer}.tag{display:inline-block;padding:3px 8px;border-radius:999px;background:#eef2f6}.new{font-weight:700}a{color:#175cd3}.stats{margin-top:10px}.footer{padding:18px 0;color:#667085;font-size:13px}@media(max-width:650px){.wrap{padding:14px}.hero{padding:16px}input{min-width:100%}}
</style></head><body><main class="wrap"><section class="hero"><h1>Summer 2027 Engineering Internships</h1><div class="muted">Daily scanner for NYC metro + remote mechanical, robotics and manufacturing opportunities.</div><div class="stats" id="stats"></div><div class="controls"><input id="q" placeholder="Search title, company, location…"><select id="status"><option value="">All relevant</option><option value="new">Preferred fields</option><option value="other">Other engineering</option></select><select id="when"><option value="">All dates</option><option value="today">Found today</option></select><button id="download">Download CSV</button></div></section><br><section class="card"><table><thead><tr><th data-k="title">Title</th><th data-k="company">Company</th><th data-k="location">Location</th><th data-k="deadline">Deadline</th><th data-k="paid">Paid</th><th data-k="cover_letter_required">Cover Letter</th><th data-k="date_found">Found</th><th>Link</th></tr></thead><tbody id="rows"></tbody></table></section><div class="footer">Generated automatically by GitHub Actions. Verify details on the employer's official posting before applying.</div></main><script>
const DATA=__DATA__; let view=[...DATA], sortKey='date_found', asc=false; const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function filter(){const q=document.querySelector('#q').value.toLowerCase(),st=document.querySelector('#status').value,wh=document.querySelector('#when').value,today=new Date().toISOString().slice(0,10);view=DATA.filter(x=>(!q||[x.title,x.company,x.location].join(' ').toLowerCase().includes(q))&&(!st||x.status===st)&&(!wh||x.date_found===today));render()}
function render(){view.sort((a,b)=>String(a[sortKey]||'').localeCompare(String(b[sortKey]||''))*(asc?1:-1));document.querySelector('#rows').innerHTML=view.map(x=>`<tr><td class="${x.status==='new'?'new':''}">${esc(x.title)}</td><td>${esc(x.company)}</td><td>${esc(x.location)}</td><td>${esc(x.deadline)}</td><td><span class="tag">${esc(x.paid)}</span></td><td>${esc(x.cover_letter_required)}</td><td>${esc(x.date_found)}</td><td><a href="${esc(x.source_url)}" target="_blank" rel="noopener">View</a></td></tr>`).join('');document.querySelector('#stats').textContent=`Showing ${view.length} of ${DATA.length} saved opportunities`}
document.querySelectorAll('#q,#status,#when').forEach(e=>e.addEventListener('input',filter));document.querySelectorAll('th[data-k]').forEach(h=>h.onclick=()=>{sortKey=h.dataset.k;asc=!asc;render()});document.querySelector('#download').onclick=()=>{let cols=['title','company','location','deadline','paid','cover_letter_required','source','source_url','date_found','status'];let csv=[cols.join(','),...view.map(x=>cols.map(k=>'"'+String(x[k]??'').replaceAll('"','""')+'"').join(','))].join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='internships.csv';a.click()};render();</script></body></html>'''.replace('__DATA__', safe_json)
    Path(output).parent.mkdir(parents=True, exist_ok=True); Path(output).write_text(page, encoding="utf-8")
